<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="81" started-at="2021-08-09T05:14:36Z" finished-at="2021-08-09T05:14:36Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="81" started-at="2021-08-09T05:14:36Z" finished-at="2021-08-09T05:14:36Z">
      <class name="TestNGSession.TestNGAnnotations">
        <test-method status="FAIL" signature="addTest()[pri:1, instance:TestNGSession.TestNGAnnotations@2be94b0f]" name="addTest" duration-ms="39" started-at="2021-08-09T10:44:36Z" finished-at="2021-08-09T10:44:36Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [300]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [300]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at TestNGSession.TestNGAnnotations.addTest(TestNGAnnotations.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addTest -->
        <test-method status="PASS" signature="subTest()[pri:2, instance:TestNGSession.TestNGAnnotations@2be94b0f]" name="subTest" duration-ms="8" started-at="2021-08-09T10:44:36Z" finished-at="2021-08-09T10:44:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- subTest -->
        <test-method status="PASS" signature="mulTest()[pri:3, instance:TestNGSession.TestNGAnnotations@2be94b0f]" name="mulTest" duration-ms="0" started-at="2021-08-09T10:44:36Z" finished-at="2021-08-09T10:44:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mulTest -->
      </class> <!-- TestNGSession.TestNGAnnotations -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
